Repository AbuTharHatem95/Hackathon-Project, pull requests merged in 2025-03, with the labels that each got.

#9 Update App.xaml
  IQDHackathon/IQDHackathon/App.xaml
  IQDHackathon/IQDHackathon/Interface.csproj
  IQDHackathon/IQDHackathon/Interface.csproj.user
  IQDHackathon/IQDHackathon/MainWindow.xaml
  IQDHackathon/IQDHackathon/MainWindow.xaml.cs
  IQDHackathon/IQDHackathon/Pages/UserControles/ctrlCheckBoxBoxes.xaml
  IQDHackathon/IQDHackathon/Pages/UserControles/ctrlCheckBoxBoxes.xaml.cs
Labels: good first issue

#11 Fixed Updating for back button and adding scroll veiwer and settingb enter button
  IQDHackathon/IQDHackathon/App.xaml
  IQDHackathon/IQDHackathon/Assets/settings.png
  IQDHackathon/IQDHackathon/Interface.csproj
  IQDHackathon/IQDHackathon/MainWindow.xaml
  IQDHackathon/IQDHackathon/MainWindow.xaml.cs
  IQDHackathon/IQDHackathon/Pages/TestScenarioGeneratorPage.xaml
  IQDHackathon/IQDHackathon/Pages/TestScenarioGeneratorPage.xaml.cs
Labels: good first issue, Good Job

#13 See this changes
  BLL/BLL.csproj
  BLL/absBaseEntity.cs
  BLL/clsExam.cs
  BLL/clsExamType.cs
  BLL/clsQuestionsType.cs
  BLL/clsSchool.cs
  BLL/clsSettings.cs
  BLL/clsStage.cs
  BLL/clsStageSubject.cs
  BLL/clsSubject.cs
  BLL/clsSubjectQuestionTypesStages.cs
  BLL/clsTeacher.cs
  DAL/DAL.csproj
  DAL/clsExamTypeData.cs
  DAL/clsExamsData.cs
  DAL/clsQuestionsTypeData.cs
  DAL/clsSchoolData.cs
  DAL/clsSettingsData.cs
  DAL/clsStageData.cs
  DAL/clsStageSubjectsData.cs
  DAL/clsSubjectData.cs
  DAL/clsSubjectQuestionTypesStagesData.cs
  DAL/clsTeacherData.cs
Labels: good first issue

#15 Working For It.....
  IQDHackathon/IQDHackathon/App.xaml
  IQDHackathon/IQDHackathon/Interface.csproj
  IQDHackathon/IQDHackathon/MainWindow.xaml.cs
  IQDHackathon/IQDHackathon/Pages/QuestionsPage.xaml
  IQDHackathon/IQDHackathon/Pages/QuestionsPage.xaml.cs
  IQDHackathon/IQDHackathon/Pages/TestScenarioGeneratorPage.xaml
  IQDHackathon/IQDHackathon/Pages/TestScenarioGeneratorPage.xaml.cs
  IQDHackathon/IQDHackathon/Pages/UserControles/ctrlCheckBoxBoxes.xaml
  IQDHackathon/IQDHackathon/Pages/UserControles/ctrlCheckBoxBoxes.xaml.cs
  IQDHackathon/IQDHackathon/Pages/UserControles/ctrlDynamicListControl.xaml
  IQDHackathon/IQDHackathon/Pages/UserControles/ctrlDynamicListControl.xaml.cs
Labels: help wanted, needs review 👀

#16 Updated TestScenarioGeneratorPage, and Pages Folder
  IQDHackathon/IQDHackathon/Interface.csproj
  IQDHackathon/IQDHackathon/MainWindow.xaml
  IQDHackathon/IQDHackathon/Pages/QuestionsPage.xaml
  IQDHackathon/IQDHackathon/Pages/TestScenarioGeneratorPage.xaml
  IQDHackathon/IQDHackathon/Pages/TestScenarioGeneratorPage.xaml.cs
  IQDHackathon/IQDHackathon/Pages/UserControles/ctrlCheckBoxBoxes.xaml
  IQDHackathon/IQDHackathon/Pages/UserControles/ctrlDynamicListControl.xaml
Labels: Good Job, ready to merge ✅

#17 Update On Page File
  IQDHackathon/IQDHackathon/Interface.csproj
  IQDHackathon/IQDHackathon/MainWindow.xaml.cs
  IQDHackathon/IQDHackathon/Pages/QuestionsPage.xaml
  IQDHackathon/IQDHackathon/Pages/QuestionsPage.xaml.cs
  IQDHackathon/IQDHackathon/Pages/TestScenarioGeneratorPage.xaml
  IQDHackathon/IQDHackathon/Pages/TestScenarioGeneratorPage.xaml.cs
  IQDHackathon/IQDHackathon/Pages/UserControles/ctrlCheckBoxBoxes.xaml.cs
  IQDHackathon/IQDHackathon/Pages/UserControles/ctrlDynamicListControl.xaml
  IQDHackathon/IQDHackathon/Pages/UserControles/ctrlDynamicListControl.xaml.cs
Labels: documentation

#20 Update On User Control ctrlCheckBox
  IQDHackathon/IQDHackathon/Interface.csproj
  IQDHackathon/IQDHackathon/Pages/QuestionsStyles.xaml.cs
  IQDHackathon/IQDHackathon/Pages/TestScenarioGeneratorPage.xaml
  IQDHackathon/IQDHackathon/Pages/UserControles/ctrlAddBrach.xaml.cs
  IQDHackathon/IQDHackathon/Pages/UserControles/ctrlCheckBoxBoxes.xaml
  IQDHackathon/IQDHackathon/Pages/UserControles/ctrlCheckBoxBoxes.xaml.cs
  IQDHackathon/IQDHackathon/Pages/UserControles/ctrlDynamicListControl.xaml.cs
  IQDHackathon/IQDHackathon/Pages/UserControles/ctrlQustionListView.xaml.cs
Labels: documentation
